import { pathExists, readTextFile, writeTextFileIfChanged } from './fs';

const MANAGED_MARKER = 'Generated by Tenex';

export interface GeneratedFile {
  filePath: string;
  contents: string;
  managed?: boolean;
}

export function makeManagedSource(contents: string): string {
  return `// ${MANAGED_MARKER}. Manual edits may be overwritten.\n${contents}`;
}

export async function assertNoGeneratedFileConflicts(
  files: GeneratedFile[]
): Promise<void> {
  const conflicts: string[] = [];

  for (const file of files) {
    if (!(await pathExists(file.filePath))) {
      continue;
    }

    const current = await readTextFile(file.filePath);
    if (current !== file.contents && !canOverwriteManagedFile(current, file)) {
      conflicts.push(file.filePath);
    }
  }

  if (conflicts.length === 0) {
    return;
  }

  throw new Error(
    [
      'Tenex would overwrite files that are not currently managed by the requested scaffold.',
      'Resolve these conflicts manually or remove the files before retrying:',
      ...conflicts.map((filePath) => `- ${filePath}`),
    ].join('\n')
  );
}

export async function writeGeneratedFiles(
  files: GeneratedFile[]
): Promise<void> {
  for (const file of files) {
    await writeTextFileIfChanged(file.filePath, file.contents);
  }
}

function canOverwriteManagedFile(
  current: string,
  file: GeneratedFile
): boolean {
  return Boolean(file.managed && current.startsWith(`// ${MANAGED_MARKER}`));
}
