import { join } from 'node:path';
import { writeTextFileIfChanged } from './fs';
import {
  addonEnvRequirements,
  formatAddonSummary,
  type TenexManifest,
} from './tenex-config';

export async function writeProjectReadme(
  projectDir: string,
  manifest: TenexManifest
): Promise<void> {
  const contents = `# ${manifest.projectName}

Generated by Tenex with the \`${manifest.template}\` template.

## Stack

- TanStack Start
- Convex
- Better Auth
- Addons: ${formatAddonSummary(manifest).join(', ')}

## First Run

\`\`\`bash
tenex doctor
tenex dev
\`\`\`

## Required Env Vars

${addonEnvRequirements(manifest)
  .map((envVar) => `- \`${envVar}\``)
  .join('\n')}

## Commands

- \`tenex doctor\` validates required env vars from \`tenex.json\`
- \`tenex dev\` runs Convex and the app together
- \`tenex deploy\` writes a production handoff and runs the Convex deploy step
`;

  await writeTextFileIfChanged(join(projectDir, 'README.md'), contents);
}

export async function writeDeployHandoff(
  projectDir: string,
  manifest: TenexManifest
): Promise<void> {
  const contents = `# Tenex Deploy Handoff

Project: ${manifest.projectName}
Template: ${manifest.template}
Package manager: ${manifest.packageManager}

## Addons

${formatAddonSummary(manifest)
  .map((item) => `- ${item}`)
  .join('\n')}

## Required Env Vars

${addonEnvRequirements(manifest)
  .map((envVar) => `- ${envVar}`)
  .join('\n')}

## Production Checklist

- Confirm provider credentials are present for every enabled addon.
- Confirm Convex deployment succeeded.
- Run the framework deploy step for your preferred host.
- Verify auth, pricing, onboarding, and admin surfaces after deploy.
`;

  await writeTextFileIfChanged(join(projectDir, 'TENEX_HANDOFF.md'), contents);
}
